// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZOzb2rUmCdKOG0l2NjZ7Au93XmpPigPs',
    appId: '1:271595048731:web:7b86db8b0a33ecc7820dbe',
    messagingSenderId: '271595048731',
    projectId: 'studenttradepost',
    authDomain: 'studenttradepost.firebaseapp.com',
    storageBucket: 'studenttradepost.appspot.com',
    measurementId: 'G-EYYLN3QN3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ViWP_Zopi6D2bbPfFshtssVi3XX7eTk',
    appId: '1:271595048731:android:49ffe3b75ac00363820dbe',
    messagingSenderId: '271595048731',
    projectId: 'studenttradepost',
    storageBucket: 'studenttradepost.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHpkaxXbXVfZMWep3IvTOQjDW_tMyfyME',
    appId: '1:271595048731:ios:60228a1d9dfec7ff820dbe',
    messagingSenderId: '271595048731',
    projectId: 'studenttradepost',
    storageBucket: 'studenttradepost.appspot.com',
    iosClientId: '271595048731-74t8n4u8tivlo1gbbd635d8nbdlt6gma.apps.googleusercontent.com',
    iosBundleId: 'com.sheridan.studentTradePostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHpkaxXbXVfZMWep3IvTOQjDW_tMyfyME',
    appId: '1:271595048731:ios:60228a1d9dfec7ff820dbe',
    messagingSenderId: '271595048731',
    projectId: 'studenttradepost',
    storageBucket: 'studenttradepost.appspot.com',
    iosClientId: '271595048731-74t8n4u8tivlo1gbbd635d8nbdlt6gma.apps.googleusercontent.com',
    iosBundleId: 'com.sheridan.studentTradePostApp',
  );
}
